# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 15:54
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_auto_20170831_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightshowstep',
            name='color',
            field=colorful.fields.RGBColorField(default='green'),
        ),
    ]
